spring:
  autoconfigure.exclude: |
    org.springframework.ai.autoconfigure.azure.openai.AzureOpenAiAutoConfiguration,
    org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration
  ai.openai:
    chat:
      options.temperature: 1.0
    image.options:
      model: dall-e-3
    api-key: