apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-finder-openai
spec:
  selector:
    matchLabels:
      app: recipe-finder-openai
  template:
    metadata:
      labels:
        app: recipe-finder-openai
    spec:
      containers:
        - env:
          - name: SPRING_DOCKER_COMPOSE_ENABLED
            value: "false"
          - name: SPRING_PROFILES_ACTIVE
            value: openai
          - name: SPRING_AI_OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                key: api-key
                name: recipe-finder-openai
          - name: SPRING_AI_VECTORSTORE_REDIS_URI
            value: redis://recipe-finder-redis:6379
          image: harbor.main.emea.end2end.link/tsalm/recipe-finder
          name: workload
---
apiVersion: v1
kind: Secret
metadata:
  name: recipe-finder-openai
stringData:
  api-key: $SPRING_AI_OPENAI_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-openai
spec:
  type: LoadBalancer
  selector:
    app: recipe-finder-openai
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-finder-redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        -   image: redis/redis-stack-server
            name: workload
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-finder-redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379